### ISSUE TITLE
NetBox v3.0 Support

### ISSUE THREAD

**Issue by ryanmerolle** [991jo/netbox_capirca_plugin#2]
As an FYI here is what changed that could impact or help the plugin:
- HTML Template updates (support change from bootstrap 3 to bootstrap 5)
- Overall UI tweaks
- Custom Queue Support for Plugins netbox-community/netbox/issues/6651

If you find any issues or have any questions feel free to hit us on the slack or add a bug /issue or add to the umbrella UI issue netbox-community/netbox/issues/6797

**Comment by 991jo** [comment]
Yes, I know this, so far I did not have the time to check out the new beta version, but this plugin should get the required updates at worst a couple of days after the 3.0 release.

**Comment by ryanmerolle** [comment]
No worries.  Just a courtesy issue from the netbox project to some of the popular plugins.  We can close the issue if you like.

**Comment by 991jo** [comment]
Finally completed this one... "a couple of days" turned out to be half a year :D

**Comment by ryanmerolle** [comment]
@991jo life happens.  It is nice that you are even maintaining this project in an public, open source way.  Thanks!
