### ISSUE TITLE
<class 'django.template.exceptions.TemplateDoesNotExist'>

### ISSUE THREAD

**Issue by dover1987** [991jo/netbox_capirca_plugin#3]
Hi!
After installing the plugin and clicking on 'ACL' button I get this error. How can I fix it?
At the same time API for this plugin works well and entities are created successfuly.

![image](https://user-images.githubusercontent.com/51654296/136983870-5e4cdc55-2aa0-4c63-acf2-f57ac0dc43b2.png)

**Comment by 991jo** [comment]
you are running on NetBox 3. So far I did not have the time to adjust the code for NetBox 3. Things got in the way, priorities changed and it may take me a couple of weeks to fix that.

**Comment by dover1987** [comment]
Thank you for the answer.
Anyway the idea of this plugin for ACl  is awesome and very handy!

**Comment by 991jo** [comment]
I finally have found the time to complete this. The Plugin is now compatible with NetBox version 3.
Feel free to give it a try and report back if you have any issues.

**Comment by dover1987** [comment]
Thank you , 
I get the error NoDefinitionsError. Could you tell me how to resolve it? I guess some files are missing in defs folder?  Monday, 07 February 2022, 04:37PM +03:00 from Jo  ***@***.*** :

**Comment by dover1987** [comment]
Works fine, thank you. 
You know what, first I thought this plugin is just a gui for creating ACLs as we do it on network devices. But now I understand that its time to read about Caprica module more closely  Monday, 07 February 2022, 04:37PM +03:00 from Jo  ***@***.*** :

**Comment by 991jo** [comment]
> I get the error NoDefinitionsError. Could you tell me how to resolve it? I guess some files are missing in defs folder?
Currently caprica wants some definitions in the corresponding directory.
So far I did not have a real issue with that because I always have some dummy definitions (like RFC1918 networks and some standard ports like DNS/SSH/HTTP/HTTPS) around.
